### ISSUE TITLE
Support for HT1632C

### ISSUE THREAD

**Issue by ericandrewlewis** [rwaldron/johnny-five#1000]
This was [sorta asked previously](https://github.com/rwaldron/johnny-five/issues/577), but the conversation ended up about the `HT16K33` rather than the `HT1632C`.

Can we add support for `HT1632C` to Johnny Five? This drives a [16x24 Adafruit matrix](https://www.adafruit.com/product/555) I just got.

**Comment by dtex** [comment]
Hi @ericandrewlewis ,

Johnny-Five contributors and maintainers are loathe to close issues where someone has a need. We don't want anyone to ever feel that we don't care, but we just haven't gotten to this feature yet. Rather than leave it languishing as an open issue we have created a [Requested Features](../wiki/Requested-Features) page and added your request for the HT1632C there.
