### ISSUE TITLE
LSM9DS0

### ISSUE THREAD

**Issue by teuteuguy** [rwaldron/johnny-five#1072]
Any chance that Johnny Five can support this sensor ?

9 degrees of freedom

**Comment by rwaldron** [comment]
I started working on this last week, I will update when I have something worth testing.

**Comment by teuteuguy** [comment]
hey rwaldron, any news on this by any chance ?

**Comment by gpkc** [comment]
I'd like to be able to use this one too. Any news?

**Comment by dtex** [comment]
Hi @teuteuguy and @gpkc ,

Johnny-Five contributors and maintainers are loathe to close issues where someone has a need. We don't want anyone to ever feel that we don't care, but we just haven't gotten to this feature yet. Rather than leave it languishing as an open issue we have created a [Requested Features](../wiki/Requested-Features) page and added your request for the LSM9DSO there.
