### ISSUE TITLE
Light: TSL2591 controller

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#1105]
@burgo4 this is all yours

**Comment by rwaldron** [comment]
Here's what's done in Light so far: https://github.com/rwaldron/johnny-five/blob/master/lib/light.js

**Comment by dtex** [comment]
Hi @rwaldron and @burgo4 ,

Johnny-Five contributors and maintainers are loathe to close issues where someone has a need. We don't want anyone to ever feel that we don't care, but we just haven't gotten to this feature yet. Rather than leave it languishing as an open issue we have created a [Requested Features](../wiki/Requested-Features) page and added your request for the TSL2591 there.
