### ISSUE TITLE
Proximity: update fixed point values to match datasheets for fractional digit accuracy 

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#1123]
To better understand what needs to be done here, take a look at this example from the `Thermometer` class: 
- https://github.com/rwaldron/johnny-five/blob/master/lib/thermometer.js#L480-L499

And the corresponding tests: 
- https://github.com/rwaldron/johnny-five/blob/master/test/thermometer.js#L692

Use the `digits.fractional(value)` function to get the number of fractional digits in a given value.

**Comment by rwaldron** [comment]
Sorry for the confusion here, I filed this from a mobile device and I fat fingered a few incorrect labels.

**Comment by henricavalcante** [comment]
Can I try this one?

**Comment by droidenator** [comment]
I'm looking into this issue and just wanted to be sure it hasn't already been resolved. When I look into proximity.js, I see a lot of `toCm` methods that look like this

```
    toCm: {
      value: function(raw) {
        return toFixed(12343.85 * Math.pow(raw, -1.15), 2);
      }
    }
```

But then I see other ones like

```
    toCm: {
      value: function(raw) {
        // http://www.maxbotix.com/articles/032.htm
        return raw / 2;
      }
    }
```

I'm assuming all return values need to be run through `toFixed`? Also, some are set to return 2 digits after the decimal, others 3 digits. I looked at the datasheets but I didn't see any clear indication why one might return 3 digits instead of 2 or 0.
