### ISSUE TITLE
J5 and SIM800l

### ISSUE THREAD

**Issue by rudemex** [rwaldron/johnny-five#1136]
works?...

thanks!

**Comment by dtex** [comment]
Sorry nobody responded. I'm guessing nobody knew what a SIM800 was. The short answer, not yet but it could. 

What would be your use case?

**Comment by dtex** [comment]
Hi @rudemex,

Johnny-Five contributors and maintainers are loathe to close issues where someone has a need. We don't want anyone to ever feel that we don't care, but we just haven't gotten to this feature yet. Rather than leave it languishing as an open issue we have created a Requested Features page and added a request for a new "GSM/Cellular" class with your device.

**Comment by ahsath** [comment]
Looking forward to this
