### ISSUE TITLE
SHT1x sensor support

### ISSUE THREAD

**Issue by rbosneag** [rwaldron/johnny-five#1233]
Guys, I just discovered this library and it's awesome. 

I'm a newbie in the RasPi world and so far I struggled with wires and low level libraries written in Python or C (although I come from the JavaScript world) so it was a great relief to find Johnny5.

I have a Sensirion [SHT11](https://www.amazon.com/SENSIRION-SHT11-HUMIDITY-SENSOR-100%25/dp/B01LWU2HR5/ref=sr_1_21?ie=UTF8&qid=1475328571&sr=8-21&keywords=sht11) temperature and humidity sensor and I managed to make it work from _Python_ (using [pi-sht1x](https://pypi.python.org/pypi/rpiSht1x/1.2) library) and _NodeJs_ (with [pi-sht1x](https://github.com/keito/pi-sht1x) which was abandoned 3y ago, is outdated and I wonder if I can trust it). I guess that both libraries are based on John Burns' C library [here](https://www.john.geek.nz/2012/08/reading-data-from-a-sensirion-sht1x-with-a-raspberry-pi/).

I was wondering if the SHT31 code in your library could be easily converted to support also SHT1x family of sensors. I'd love to help but I'm new to this IoT world and fear to break things.

SHT1x datasheet for communication with the sensor is [here](https://cdn-shop.adafruit.com/datasheets/Sensirion_Humidity_SHT1x_Datasheet_V5.pdf), detailed from page 6.

Any help would be greatly welcomed.

**Comment by dtex** [comment]
Hi @rbosneag ,

Johnny-Five contributors and maintainers are loathe to close issues where someone has a need. We don't want anyone to ever feel that we don't care, but we just haven't gotten to this feature yet. Rather than leave it languishing as an open issue we have created a [Requested Features](../wiki/Requested-Features) page and added your request for the SHT11 (and variants) there.
