### ISSUE TITLE
Maybe ship Firmata firmware with johnny five?

### ISSUE THREAD

**Issue by cookiengineer** [rwaldron/johnny-five#1339]
Hey guys,

I just started playing around with johnny-five for the first time on a project. My setup was plain and had nothing related to arduino / AVR on it. To be honest, I spent around 3 hours of time just figuring out what I actually need to install and run in order to get going. The website is pretty amazing with all the cables and schematics, but the installation process is a real big pain for newcomers that have no effing clue what's going on. After around 20 errors I was close to the edge of just doing something else.

Current manual steps:

- Read the updated docs (I already fixed the [Getting Started](https://github.com/rwaldron/johnny-five/wiki/Getting-Started) guide).
- Figure out that johnny five requires a firmware on Arduino (~10min)
- Install Arduino tools (or package on Unices)
- Install necessary libraries required by StandardFirmataPlus firmware (took 30 minutes to google because of shitty forum posts)
- Figure out how to compile stuff without shitty IDE with dozens of header errors (~15min to find the manpage of arduino, which essentially has literally no information on boards - so I put it in the johnny five wiki).
- Compile firmata firmware and flash stuff on Arduino
- Now actually be ready to test the Getting Started code

This can be eased up. Very much. All steps except the first and last one could be automated with a simple helper script, no matter if it's a bash script or a nodejs script or something else.

Would it make sense to simply ship the StandardFirmataPlus firmware with johnny five and suggest a "flash board" option to initialize the board? Something like `johnny-five autofix` or so?

**Comment by rwaldron** [comment]
Thanks for contributing updates. This project has always assumed that if the user is here, then they are likely already familiar with Node.js and will have that installed. 

> - Read the updated docs (I already fixed the Getting Started guide).

Thanks! Maybe @dtex or @lyzadanger review those changes :)

> - Figure out that johnny five requires a firmware on Arduino (~10min)
> - Install Arduino tools (or package on Unices)

Yes, this is stated on the readme of this repo: https://github.com/rwaldron/johnny-five#setup-and-assemble-arduino. All you need is the Arduino IDE. 

> - Install necessary libraries required by StandardFirmataPlus firmware (took 30 minutes to google because of shitty forum posts)

All Arduinos ship with StandardFirmata preloaded on them. We recommend using StandardFirmataPlus, but StandardFirmata is totally valid. 

> - Figure out how to compile stuff without shitty IDE with dozens of header errors (~15min to find the manpage of arduino, which essentially has literally no information on boards - 

Sorry, but that's Arduino project, not Johnny-Five. Just install the IDE from this page: https://www.arduino.cc/en/Main/Software (or not, since StandardFirmata comes pre loaded on the board, out of the box)

> so I put it in the johnny five wiki).

Thanks, but all of that is really confusing and has never, ever been necessary in five year history of this project :|


> Compile firmata firmware and flash stuff on Arduino

It's as easy as pressing the "Upload" button from the IDE. 


> Now actually be ready to test the Getting Started code

Honestly, it works out of the box. For the last 5 years I've been doing workshops with attendance ranging from one person to over a hundred, people using OSX, Linux and Windows, and I've never encountered the pain path that you describe above. 

> Would it make sense to simply ship the StandardFirmataPlus firmware with johnny five

No, not at all—but thank you for asking first.
