### ISSUE TITLE
Binding issue OSX Sierra : how to fix

### ISSUE THREAD

**Issue by Antoinebr** [rwaldron/johnny-five#1385]
Hi I struggled a lot to install j5 on my macbook OSX sierra. 

Here how I fixed it ( if this can help ) 

Error message I got on my first try : 

```Uncaught Error: Could not locate the bindings file. Tried: ```

This mean there's a issue with ```node_modules/serialport```

First install node-gyp : https://github.com/nodejs/node-gyp

Check if Xcode is installed by typing : 
```xcode-select -p``` 
 if you see ```/Applications/Xcode.app/Contents/Developer``` that's mean is already install otherwise install it 
```xcode-select --install```

now run ```npm install serialport```

It worked for me, hope this will help some of you.

**Comment by dtex** [comment]
Thanks for sharing the tip @Antoinebr 

If anyone else is having problems with serialport installation, be sure to check out their [installation instuctions](https://github.com/node-serialport/node-serialport#installation-instructions). It would be confusing to try and cover all that here in Johnny-Five, since the serialport/firmata use case is just one of many.
