### ISSUE TITLE
Sensor disable function only work once

### ISSUE THREAD

**Issue by riodajs** [rwaldron/johnny-five#1520]
I have this code:
```
myBoard.on("ready", function(){
  myMic = new Sensor("A0", {"enabled": false});
  myLed = new Led(13);
  setInterval(function(){
      myMic.enable();
      console.log("Mic ON");
      myMic.on("data", (val) => {
        console.log("Analogico: " + val);
      });
      myMic.disable();
      console.log("Mic OFF");
    }
  }, 3000);
});
```
The microphone is only deactivated once, then the disable function look does not work correctly.

**Comment by dtex** [comment]
At first blush it looks like state.enabled isn't managed properly in the ```enable()``` method. I won't be able to look at it until tomorrow, but maybe somebody else will see the issue before then.

**Comment by dtex** [comment]
Okay, looking a little closer that may not be the problem here. 

Are you just wanting to get a reading once every three seconds?

**Comment by dtex** [comment]
Some comments about your code:

Sensor params can be ```Sensor(pin)``` or ```Sensor(opts)```.  This is the correct signature for what you want to do:

````js
myMic = new Sensor({ pin: "A0", "enabled": false});
````

In your setInterval function you are adding an additional listener every three seconds. That should be added just one time, outside the interval:
````js
myMic.on("data", (val) => {
  console.log("Analogico: " + val);
});
````

But I don't think you even need the setInterval. It looks like you are trying to get a reading once every three seconds. I don't think your code will ever do that since the enable, disable and console log commands are synchronous and the sensor will never be enabled when data is received. I think this is what you want:
````js
const five = require("johnny-five");
const myBoard = new five.Board();

myBoard.on("ready", function(){
  myMic = new five.Sensor({ pin: "A0", "freq": 3000});
  myMic.on("data", (val) => {
    console.log("Analogico: " + val);
  });
});
````
All that said, there may still be a bug in enable/disable but it shouldn't be a blocker for you.

**Comment by riodajs** [comment]
Thanks, but this was only an example, the idea is create a button to enable and disable the sensor.

**Comment by Tsteinroesland** [comment]
I'm also seeing this issue with a very simple approach:

Code to reproduce:

```const { Board, Sensor } = require('johnny-five')

const board = new Board({
  port: 'COM3',
})

board.on('ready', () => {
  const moistureSensor = new Sensor({
    pin: 'A0',
    freq: 100,
  })

  moistureSensor.on('data', value => {
    console.log(value)
  })

  setTimeout(() => {
    console.log('Disable')
    moistureSensor.disable()
  }, 1000)

  setTimeout(() => {
    console.log('Enable')
    moistureSensor.enable()
  }, 2000)

  setTimeout(() => {
    console.log('Disable')
    moistureSensor.disable()
  }, 3000)
})
```

Console:
>> 413
413
413
413
413
413
413
413
413
Disable
Enable
413
413
413
413
413
413
413
413
413
Disable
413
414
[.... Keeps logging forever]
