### ISSUE TITLE
"Hello World" not working

### ISSUE THREAD

**Issue by hellopat** [rwaldron/johnny-five#156]
Environment
- OSX 10.8.4
- node v0.10.22 (had issue on v0.10.5 as well, then upgraded)
- Johnny-Five (master branch)
- Firmata 2.3.1
- Arduino Uno R3 Board

When running the program (`node index.js`) containing the standard hello world code, the following output occurs:

```
➜  garduino  node index.js
1372950025750 Board Connecting...
1372950025758 Serial Found possible serial port /dev/cu.usbmodemfa141
1372950025759 Board -> Serialport connected /dev/cu.usbmodemfa141
1372950029107 Board <- Serialport ready /dev/cu.usbmodemfa141
1372950029108 Repl Initialized
>> 
```

The LED connected properly to GND and PIN13 blinks 2 times..pauses..blinks 2 times... pauses.. blinks 3 times, then stops.

The console output for `board.ready` is true and the ready event callback fires.

Any ideas?  Let me know if you need more information.

**Comment by Oyamasiphula** [comment]
I had a similar issue and finally a Blink file still works fine even when I'm getting the 

```
1514300638808 Connected COM7
1514300642562 Repl Initialized
>>
```
and my js code is as follows
```javascript
var five = require('johnny-five');
const board = new five.Board({ port: "COM7" });

  board.on("ready", function() {

    // Create an Led on pin 13 and strobe it on/off
    // Optionally set the speed; defaults to 100ms
    var alertLedPin = new five.Led(12),
        piezoElement = new five.Piezo(3);

  this.repl.inject({
    alertLedPin:alertLedPin,
    speaker: piezoElement
  })
    piezoElement.play({
      // song is composed by a string of notes
      // a default beat is set, and the default octave is used
      // any invalid note is read as "no note"
	  song: "G G A A G G A A G G A A A G G A A G G A A G G ",
      beats: 1 / 4,
      tempo: 100
    });
    alertLedPin.strobe(100);
  });

```
I think people might assume that the script doesn't get executed by node instead it will be like they have to write a functional code on the cmd which is not necessarily needed.

I once had this problem with windows 7 otherwise on (linux based OS's) everything works fluently and there is no extra configuration like to use the IDE to configure a correct port.
