### ISSUE TITLE
Board events not documented

### ISSUE THREAD

**Issue by kula124** [rwaldron/johnny-five#1630]
Hello!
The only event I knew of is the "ready" event. After going through source code for board I found few more like "close", "disconnect", "error" and "string". 
I'm looking for a event that fires if the connection is lost. My BT module works fine but after some time it disconnects. This is probably due my poor battery setup but still it would be nice if there was an emit letting me know this is happening so I can handle the reconnect code myself. 
The other events are not documented at all. BTW none of them fires on disconnect. I figured out when "error" fires based on source code but I'm not really getting the other ones. 
I'm willing to write the docs for this if someone can clue me in into what they do.

**Comment by MintyMods** [comment]
Hi @n00ne1mportant,

I found the [events ](http://johnny-five.io/api/board/#events) to be documented well against the J5 Board. Tripped me up at first because I expected to see the events higher up in the documentation but I think it is correct for them to be in the board. I just bookmark that page now :)
