### ISSUE TITLE
Stop stepper while running

### ISSUE THREAD

**Issue by Torsten85** [rwaldron/johnny-five#1836]
Hello,

is it possible to stop a stepper while its running? I need an "emergency stop" function, but I don't see a way to cancel the ongoing steps.

**Also one additional stepper related question (I don't want to make another issue for that):**
Could someone briefly explain the parameters for accel / decel to me? The docs show this:

```js
//   - Accelerate over the first 1600 steps
//   - Decelerate over the last 1600 steps

stepper.step({ steps: 2000, direction: 1, accel: 1600, decel: 1600 }, function() { console.log("Done stepping!") })
```
which does not make much sense to me.  To fully accelerate / decelarate, there should be at least 3200 steps right? Makes a higher number a faster acceleration?

Thanks in advance.

**Comment by dtex** [comment]
Johnny-Five's stepper class targeted [firmata's legacy stepper](https://github.com/firmata/protocol/blob/master/stepper-legacy.md) protocol (which was just "stepper" back then) and legacy stepper does not support stop. 

Since then, [accelStepper has been added to firmata](https://github.com/firmata/protocol/blob/master/accelStepperFirmata.md), and it does support stop (along with many other things). Unfortunately, it has not made the leap to Johnny-Five. It is possible to use Accel Stepper directly on the board object (assuming you are using firmata) if you still want to use Johnny-Five for other things.

[AccelStepperFirmata documentation](https://github.com/firmata/protocol/blob/master/accelStepperFirmata.md)
[Example program](https://github.com/firmata/firmata.js/blob/master/packages/firmata.js/examples/stepper-accel.js)

**Comment by Torsten85** [comment]
@dtex Thanks that helps a lot! Didn't even know there was a firmata.js! I'll close this issue then.
