### ISSUE TITLE
DC motor and Servo

### ISSUE THREAD

**Issue by leyenda** [rwaldron/johnny-five#309]
Hello everyone, Im using an L298n to control one dc-motor and Im setting the arduino UNO pin 9 as PWM just how the documentation indicates. 

```
this.pinMode(9, five.Pin.PWM);
```

Everything works great until I declare a servo 

```
servo = new five.Servo(11);
```

After that the pin9 doesnt seems to be working as PWM and only enable the motor at 255 value.

Any help would be apreciate.
Thanks

**Comment by markwest1972** [comment]
Hello!  

I just came across this issue while trying to solve a problem with my robot, which is based on an Pololu Zumo Chassis.  I'm having the same problem, as the chassis motors are connected to pins 9 & 10.  

When adding servos to my robot the net effect that I can no longer control the speed of these motors.

Unfortunately the robot is a bit tricky to dismantle, so I just wondered if you could think of any possible workarounds (alternative Firmata libraries)?

Thanks in advance for any help you can give me!

Mark

**Comment by rwaldron** [comment]
@markwest1972 

> Unfortunately the robot is a bit tricky to dismantle, so I just wondered if you could think of any possible workarounds (alternative Firmata libraries)?


Well, there is actually no software for any platform that can fix this because the Zumo is hard wired to use pin 9 and 10 for PWM speed control of the two motors. https://www.pololu.com/docs/0J57/5


> When adding servos to my robot the net effect that I can no longer control the speed of these motors.

Are they connected to 9 and 10? What about using other PWM capable pins?

**Comment by markwest1972** [comment]
@rwaldron thanks for a quick reply!

Unfortunately, according to @soundanalogous, the servo library disables analogWrite() (PWM) functionality on pins 9 and 10.  As the Zumo is hard wired to use pin 9 and 10 I guess I'm pretty stuck, no matter which pins I connect the servos to.

I see that this is a problem whether I use Johnny-Five or native Arduino :(

Anyway, I've posted a question on the Pololu forums, asking about the possibilities of requiring the Zumo.  I guess I'll have to wait and see what they say.

**Comment by rwaldron** [comment]
> Unfortunately, according to @soundanalogous, the servo library disables analogWrite() (PWM) functionality on pins 9 and 10.

It disables the literal call to `analogWrite` on those pins, but doesn't flat out disable them. Those two pins can still be controlled with a `board.servoWrite(pin, 0-180)` call (which results in a call to `servo.write(pin, 0-180)` on the board). All you'd need to do is `five.Fn.map(speed, 0, 255, 0, 180)` to map the speed value.

**Comment by markwest1972** [comment]
Ok, I just need to think about how that would work....

At the moment I used the following commands to set up and control the motors on the Zumo chassis.

> var leftMotor = new five.Motor([10, 8]);
> var rightMotor = new five.Motor([9, 7]);
> ....
> leftMotor.fwd( 100 );
> rightMotor.fwd( 100 );

How would I add the board.servoWrite(pin, 0-180) calls to this code?

**Comment by rwaldron** [comment]
Let's ask @dtex 

I think it might make sense for the `Motor` class to use `servoWrite` internally, instead of `analogWrite`, but Donovan will know if there are issues with that. 

In the meantime, give this a try: 

```js
five.Motor.prototype.setPWM = function(pin, value) {
  if (this.io.pins[pin].mode !== this.io.MODES.SERVO) {
    this.io.pinMode(pin, this.io.MODES.SERVO);
  }
  this.io.servoWrite(pin, five.Fn.map(value, 0, 255, 0, 180));
};

var leftMotor = new five.Motor([10, 8]);
var rightMotor = new five.Motor([9, 7]);

leftMotor.fwd( 100 );
rightMotor.fwd( 100 );
```

This just overrides the present definition of `setPWM`. I have no idea if it will work, but it seems like it should. If it does, then that buys time for Johnny-Five to implement proper support for the Zumo shield.

**Comment by markwest1972** [comment]
Thanks a lot!  I'll give that a try tomorrow (it's wine o'clock here in Oslo and time to put the robot to bed for the night).

As always, thanks for your help!  I really appreciate it!

**Comment by rwaldron** [comment]
Enjoy your evening! 

> As always, thanks for your help! I really appreciate it!

No problem :) 

I will see about assembling my zumo as well and we'll get to the bottom of this together.

**Comment by dtex** [comment]
I had it in my head that servoWrite handled the value differently, but I found this in firmata.js:

https://github.com/jgautier/firmata/blob/master/lib/firmata.js#L657-L661
````
Board.prototype.servoWrite = function(pin, value) {
  // Values less than 544 will be treated as angles in degrees
  // (valid values in microseconds are handled as microseconds)
  this.analogWrite.apply(this, arguments);
};
````
So I don't see what difference it would make.

**Comment by rwaldron** [comment]
> I had it in my head that servoWrite handled the value differently, but I found this in firmata.js:

Ah, yes. It's the pin's _mode_ that matters: https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino#L299-L315

So you _could_ set the pinMode to 4 (servo) and still call analogWrite

**Comment by dtex** [comment]
God I hope I'm just exhausted and overlooking something obvious, but I'm beginning to think the range is not being mapped properly at all. I don't see where we are mapping degrees [0, 180] to our PWM range [0, 255]. It's doing it for the PCA9685 but not for servos connected to the Arduino's pins.

**Comment by soundanalogous** [comment]
So you can use board.servoWrite to drive a regular DC motor? Hummm, never thought of trying that.

**Comment by markwest1972** [comment]
Ok, just got up and done a test.  

The good news is that it works!  I am now able to control the speed of the motors! +1: 

The bad news is that the motors are now constantly buzzing / shaking.  This happens whether or not the additional servos are connected.  Another side effect is that the motors are now a lot slower.

**Comment by markwest1972** [comment]
In case it helps, heres a link to my question on the Pololu Forum, where they suggested using different timers to control the servos and the motors.

http://forum.pololu.com/viewtopic.php?f=29&t=9622&sid=488bde4bb7bfaa341329eafcd3bfcc10

**Comment by rwaldron** [comment]
Slowdown and jitter is likely caused by the pwm range disparity between
servo.write and analogWrite (in the C program running on the board). I had
forgotten about that, and this is probably not the right solution.

**Comment by rwaldron** [comment]
For some extra dollars, you could add an adafruit pca9685 and get 16 servos
controlled via I2C :)

**Comment by markwest1972** [comment]
That's certainly one option!  I'm also looking into remapping the 9 & 10 Pins on the Zumo Shield.  

In the mean time let me know if you've got any other ideas you'd like me to try out.  I have a test rig ready to go at a moments notice!

**Comment by soundanalogous** [comment]
You could use an Arduino Mega, but it would overhang so that may not be ideal.

**Comment by markwest1972** [comment]
@soundanalogous I'm actually using a RaspberryPI, connected to the Zumo via an Arduberry.  I'd like to keep all of this if possible, so the remapping option is currently my favourite.  But I'll keep the Mega in mind.

**Comment by markwest1972** [comment]
@soundanalogous @rwaldron Just out of interest, does Johnny-Five / Firmata do anything specific with the various timers on the ATmega chip?

**Comment by soundanalogous** [comment]
@markwest1972 StandardFirmata already uses all of the timers of an ATmega328p. The number of timers available depends on the specific microcontroller. An Arduino Mega more timers than an Arduino Uno even though both are in the ATmega chip family.

I don't think direct timer access via the Firmata protocol would be useful since you could not return any data when the timer interrupt fires (sending stream data is too big of a task to handle in an interrupt handler). It could be possible however to define higher level functions such as measuring pulse width but there would be a number of constraints. The pulse width would be calculated on timer interrupt, but it would only store the value. The value would be reported on the next iteration of the loop. While the value is being sent, interrupts should be disabled (to avoid breaking the stream transmission). This would prevent reliably reading a continuous pulse since you could miss an edge of the pulse when interrupts are disabled during data transmission.

If HW timers are exposed via Linux-based boards (Edison, Galileo, etc) that would be a better approach for accessing timers via Firmata with JavaScript. It's just too low level of a feature not to handle reliably without major tradeoffs.

**Comment by markwest1972** [comment]
@soundanalogous Thanks for your answer!  I now have a better understanding of the challenges here.

If anyone else reading this thread is interested, I found this article to be informative : http://www.engblaze.com/microcontroller-tutorial-avr-and-arduino-timer-interrupts

**Comment by markwest1972** [comment]
I just resolved this issue remapping the pins so that 9 and 10 are no longer used.  For more information on how to do this visit this thread : http://forum.pololu.com/viewtopic.php?f=29&t=9622.

Really happy now,  My PI Controlled Zumo now has a pan and tilt camera :dancers:

**Comment by rwaldron** [comment]
So awesome! Can you do a write up for the wiki (and forth coming website :D)?

**Comment by markwest1972** [comment]
Can do.  Got a lot on over the next week, but will get something down before Easter.  Heres the Robot BTW.

![markawest_2015-mar-12](https://cloud.githubusercontent.com/assets/9844371/6614071/d2d00612-c895-11e4-9563-53a59f8e7639.jpg)

She may not look like much, but she's got it where it counts, kid. I've made a lot of special modifications myself.

**Comment by Resseguie** [comment]
@markwest1972 Looks cool! Maybe I missed it earlier, but are you using teh Zumo 32U4 or the older "Zumo for Arduino" version? Just curious.

**Comment by markwest1972** [comment]
The older version.

**Comment by rwaldron** [comment]
Oh wow—that looks like a bot I've been building this week :D

![](https://dl.dropboxusercontent.com/u/3531958/edison-spy-bot.jpg)

**Comment by markwest1972** [comment]
@rwaldron Nice!  Do you have video of it in action?

**Comment by rwaldron** [comment]
@markwest1972 This project has become my albatross...

- When using wall power, the board and code work perfectly. Once I switched to LiPo power, strange things started happening.
- With a 4C, 2.25A LiPo, regulated by a 12V 3A (max) BEC: 
- The board failed to initialize the GPIOs necessary for the compiled bindings lib to detect which kind of breakout it was attached to: Arduino or Mini? It was detecting Mini, so therefore had all the pin capabilities wrong. 
- While refactoring the power source to use a BEC that regulated to 2A (max), I accidentally plugged in the power source backwards... So that Edison was toast. 
- Once I got my second Edison mounted to the board, I had to reflash, update and all that.
- I installed all the camera drivers, just as I had before, but this time, they simply would not detect the camera. This lasted for two days, at which point I gave up and started from scratch. 
- I learned that the drivers come installed on the latest edison image, so I re-flashed following the directions given by Intel. 
- Oddly, this re-flash did not delete all of my own files in the home dir on the board (it should've). 
- BUT! The camera started detecting. 
- So then I spent time tooling around with the frame rate and kb/s of the video feed. For some reason, the code that worked on the previous Edison would just crash the new one. 
- Every change I make has a 50/50 chance of crashing the board, which means I have to reboot and all that shit and it's time consuming :(

And that's where I'm at so far.

**Comment by markwest1972** [comment]
Ouch!  That sounds like hard work.  It'll be worth it when you are done though!

If you fancy a break have a look at this : https://vimeo.com/122570460.  My robot has come on a bit since Christmas, but I think it's now time to put the Zumo away and start with a new project.

**Comment by Resseguie** [comment]
@markwest1972 that's cool!

**Comment by markwest1972** [comment]
@Resseguie Thanks :)

**Comment by markwest1972** [comment]
@rwaldron Write up completed : https://github.com/rwaldron/johnny-five/wiki/Adding-Servos-to-a-Pololu-Zumo-Robot

Hope it's ok!

**Comment by Resseguie** [comment]
Seems straightforward enough to me. Thanks for the writeup!

My only minor comment is regarding "Doing this will permanently damage your Pololu Zumo!"

I'd maybe soften that to "may" instead of "will". Depends on your definition of "damage". :)

**Comment by markwest1972** [comment]
@Resseguie Good catch.  Me fix.

**Comment by Resseguie** [comment]
@markwest1972 I added one more clarification that PWM is disabled on 9 & 10. It could have been read as "all PWM is disabled" with the previous wording.

**Comment by rwaldron** [comment]
@markwest1972 that's fantastic—thanks! 


I made a couple minor edits: 

1. I saved your images to my public dropbox and updated the guide to display the images inline
2. Set the syntax highlighter to "js" for the code at the end

**Comment by markwest1972** [comment]
@Resseguie @rwaldron Thanks!

**Comment by alexcroox** [comment]
I know this is closed, but just wanted to say you saved me hours (unfortunately after already spending hours!) debugging this problem with my motor driver + servo. Switching the servos to 9/10 instead of the motors fixed it instantly. Thank you!!
