### ISSUE TITLE
Issue with `Fn.sleep`

### ISSUE THREAD

**Issue by jpetitcolas** [rwaldron/johnny-five#315]
I am encountering an issue with `Fn.sleep` function. Here is the related code:

``` js
var five = require("johnny-five");

var led;
var board = new five.Board();

board.on("ready", function() {
    led = five.Led(13);
    led.on();
    five.Fn.sleep(500);
    led.off();
});
```

Yet, the problem is the led switches off immediately (I can't even see if it switch on correctly). The circuit is good, as when I switch on the LED from `repl` it works fine.

If I replace the previous code by the following:

``` js
    led.on();
    setTimeout(function() { led.off(); }, 500);
```

It works. When looking at the `Fn.sleep` function, I can't see anything explaining this asynchrounous-like behavior. Am I missing something?

I am working with the [SparkFun Inventor's Kit](https://www.sparkfun.com/products/12001), based on an ATmega328.

**Comment by officer47p** [comment]
Hey, I know this thread has been closed but I have a question.
How can I delay in my codes just like delay function in Arduino boards?
Please help me, it's driving me crazy because this package is AWESOME and the only problem is needing for a delay function.
Thanks man, you made my work so much easier:)

**Comment by dtex** [comment]
Do you really need to stop all other code execution or do you just need something to happen a certain amount of time later? Since this is node.js I bet there is a better way than just replicating Arduino's ```delay()``` method.

If you really just want a delay-like function you can use the technique Rick described above:

> The sleep function was implemented with a while loop that continued to loop until it's condition evaluated as false, in this case until a certain amount of time had passed. Since while loops block execution, the side effect of waiting for some amount of time to pass emulates ms sleeps, but is ultimately process blocking.

Otherwise, tell us a little about your hardware and what you are trying to accomplish. Share code if you have it.
