### ISSUE TITLE
Should be able to use forEach on led instance

### ISSUE THREAD

**Issue by balupton** [rwaldron/johnny-five#414]
The following code works:

``` javascript
var j5 = require("johnny-five");
var board = new j5.Board();

board.on("ready", function() {
  var ledPins = [2,3,4,5,6,7,8,9];
  var leds = new j5.Leds(ledPins);
  for (var i = 0; i < leds.length; i++) {
    leds[i].on();
  }
});
```

However, my first attempt, which seems nicer, which doesn't work, was the following:

``` javascript
var j5 = require("johnny-five");
var board = new j5.Board();

board.on("ready", function() {
  var ledPins = [2,3,4,5,6,7,8,9];
  var leds = new j5.Leds(ledPins);
  leds.forEach(function(led){
    led.on();
  }
});
```

Perhaps having it inherit from the array prototype, or having it be an enumerable is the answer.

**Comment by icaroscherma** [comment]
Guys, sorry to comment when the Issue is already Closed. But since I figured out another (good) thing I still want to share this.

Let's say that I want to make multiple instances of ``Led`` instead of ``Leds``. Why? Well, I'm organizing an Home Automation and I want to give a Name for every room in a JSON object, and in this case later on I can still recognize which led is which.

Scenario ( ``config.json``): 
```JSON 
{
    "name" : "House of Icaro",
    "bedrooms" : { }
}
```

and then, in the ``app.js``:
```JavaScript 
// Import the Scenario (I do this after declaring the Board var)
var house = require('./config.json');

// Inside board.on ready
house.bedrooms.icaro =  new five.Led("A1");
house.bedrooms.joseph =  new five.Led("A2");
house.bedrooms.gabriel =  new five.Led("A3");

// Turn on every single Light =)
for (room in house.bedrooms) {
    house.bedrooms[room].on();
}
```

**Comment by rwaldron** [comment]
Thanks for the example!
