### ISSUE TITLE
Intermittent test failures (still)

### ISSUE THREAD

**Issue by dtex** [rwaldron/johnny-five#419]
On tests with real timers we are seeing intermittent failures at Travis CI. It also fails locally on occasion. Tasks are simply not happening in the expected time. For example, we have ~24ms of wiggle room on piezo.playtune but it occasionally does not complete in time (the expected time to complete is 36ms and we currently wait 60ms).

Ideas:

 1. Increase the timeout. I tried this and it reduced the frequency of build failures, but it ultimately feels like a sledgehammer solution to just keep cranking up the timeout.
 1. Fire an event when a tune is finished playing and check values after that instead of relying on a timeout.
 1. I haven't looked at the piezo code, but maybe we need to test the technique used for timing in piezo against Travis and profile Travis CI's performance so we know what to expect.

Lastly, @lyzadanger made an effort to minimize the added delay on tests. Do we care if the tests take an extra 100 or even 1000ms? If so, the animation tests are going to be a big problem as they're at about 12 seconds right now.

**Comment by lyzadanger** [comment]
Hi! I've been putting some thought into addressing this more systematically. I'm not going to open a PR just yet because my changes make some assumptions and raise some questions to consider.

**Assumption 1**: Some tests are failing on multiple kinds of slow hardware, so I assume that by *default* slow tests should *not* get run. That means in practice that the `grunt default` task would run a subset of all possible tests. It also means Travis would not run the complete set of slow tests (because it's running that `default` task). Because slow tests are problematic in _multiple_ contexts, it seemed like this would be the appropriate default, but if this is backwards, it nullifies my current approach.

**Assumption 2**: All tests in the `test` directory should be runnable and passing. I found a test, `distance.js`, that is not included in the list of tests in the `nodeunit` task on master. FWIW, I added it on [my branch](https://github.com/lyzadanger/johnny-five/tree/419-test-failures) and it passes just fine. 

**Assumption 3**: `bootstrap.js` test must be run before all test runs of any flavor. There are no other dependencies on test ordering. There are several "core"-ish tests listed at the top of the list in the present `Gruntfile`, but I believe this is just for human organizational sake: 

```
        "test/board.js",
        "test/board-connection.js",
        "test/compass.js",
        "test/options.js",
        "test/board.pins.js",
        "test/board.component.js",
        "test/capabilities.js",
```

**Assumption 4**: `mock-*` scripts are not tests but are supporting mechanisms for running tests.

Assumption 4a: It's not weird that `lib/board.js` references one of the `mock-` test files (that is presently the case).

**Are these assumptions correct?** If so, I have a direction I could propose.

**Comment by dtex** [comment]
Re: Assumption 1: I seem to recall that the complaint on Raspberry Pi was that the tests just took too long, not that they were failing but as you saw they even fail on a "real" computers occasionally though not nearly as often as on Travis.

**Comment by McDonnellDean** [comment]
@lyzadanger That looks perfectly on point!

**Comment by lyzadanger** [comment]
I'll do a write-up and submit a PR tonight or tomorrow night, availability-dependent!

**Comment by rwaldron** [comment]
Forgot to close!
