### ISSUE TITLE
Shift Register for input

### ISSUE THREAD

**Issue by erikbonthuys** [rwaldron/johnny-five#456]
Can functionality be added to use shift registers for input  74hc165 or CD4021B
http://www.arduino.cc/en/Tutorial/ShiftIn

**Comment by dtex** [comment]
Hi @erikbonthuys,

Johnny-Five contributors and maintainers are loathe to close issues where someone has a need. We don't want anyone to ever feel that we don't care, but we just haven't gotten to this feature yet. Rather than leave it languishing as an open issue we have created a [Requested Features](../wiki/Requested-Features) page and added your request for these two expanders there.
