### ISSUE TITLE
Support Rainbowduino

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/johnny-five#574]
- Uses **Arduino Duemilanove w/ATmega328** 
- http://www.seeedstudio.com/wiki/Rainbowduino_v3.0
- https://github.com/rwaldron/johnny-five/issues/461#issuecomment-68621750
- MY9221 controller

**Comment by dtex** [comment]
Hi @rwaldron 

Johnny-Five contributors and maintainers are loathe to close issues where someone has a need. We don't want anyone to ever feel that we don't care, but we just haven't gotten to this feature yet. Rather than leave it languishing as an open issue we have created a [Requested Features](../wiki/Requested-Features) page and added your request for Rainbowduino support there.
