### ISSUE TITLE
Refactor gripper component using controller/device model

### ISSUE THREAD

**Issue by Resseguie** [rwaldron/johnny-five#698]
Deemed too specific.

**Comment by rwaldron** [comment]
Agreed.

**Comment by rwaldron** [comment]
OR...

If we can refactor this into a controller/device model and add support for several different types of gripper components, then we can keep it.

**Comment by Resseguie** [comment]
@rwaldron So I now vote that we plan to refactor this later to the controller/device model but not let it hold up 0.9.0. You good with removing that label from this issue?

**Comment by rwaldron** [comment]
Works for me

**Comment by dtex** [comment]
So gripper is just a scalar applied to a servo and I don't believe it warrants having its own class. I'm going to argue that we move this out to a Johnny-Five module and deprecate the gripper class.

**Comment by dtex** [comment]
Hi @Resseguie ,

I caught a bit of the CodeMash drone feed... Flying those things looks hard!

Johnny-Five contributors and maintainers are loathe to close issues where someone has a need. We don't want anyone to ever feel that we don't care, but we just haven't gotten to this yet. Rather than leave it languishing as an open issue we have created a [Requested Features](../wiki/Requested-Features) page and added your request for a Gripper module.

This is like the 4th request of yours that I've closed in the past two days. Hopefully will be able to start landing some of these features soon.
