### ISSUE TITLE
how can i access max6675, max31855K

### ISSUE THREAD

**Issue by chedongzhe** [rwaldron/johnny-five#738]
how can i access max6675, max31855K with johnny-five

**Comment by dtex** [comment]
Hi @chedongzh 

Sorry nobody has gotten back to you. I suspect nobody has any first hand knowledge of these specific devices. It looks like they use SPI. How best to tackle that will depend on what MicroController you are using. Are you using an Arduino?

**Comment by rwaldron** [comment]
(Somehow I just missed it! sorry :frowning:  )

**Comment by ScrewedBrain** [comment]
It's been a year since this messages, but I'd love to see it as well.)

**Comment by ScrewedBrain** [comment]
max6675

**Comment by rwaldron** [comment]
@ScrewedBrain sorry, still no SPI in the protocol spec

**Comment by dtex** [comment]
Hi @chedongzhe and @ScrewedBrain  ,

Johnny-Five contributors and maintainers are loathe to close issues where someone has a need. We don't want anyone to ever feel that we don't care, but we just haven't gotten to this feature yet (and we still need SPI support in firmata). Rather than leave it languishing as an open issue we have created a [Requested Features](../wiki/Requested-Features) page and added your request for the MAX6675 and MAX31855K there.
